CREATE ROLE USER_READONLY;

GRANT USAGE ON WAREHOUSE DEFAULT_WH TO ROLE USER_READONLY;

GRANT USAGE ON DATABASE NOVADRIVE TO ROLE USER_READONLY;

GRANT USAGE ON SCHEMA NOVADRIVE.ANALYTIC TO ROLE USER_READONLY;

GRANT SELECT ON ALL TABLES IN SCHEMA NOVADRIVE.ANALYTIC TO ROLE USER_READONLY;

GRANT SELECT ON FUTURE TABLES IN SCHEMA ANALYTICS.PUBLIC TO ROLE USER_READONLY;


CREATE USER USER_BI
PASSWORD='...'
DEFAULT_ROLE=USER_READONLY
DEFAULT_WAREHOUSE=DEFAULT_WH
MUST_CHANGE_PASSWORD=FALSE;

GRANT ROLE USER_READONLY TO USER USER_BI;

ALTER USER USER_BI SET DISABLE_MFA = TRUE;

GRANT USAGE ON ALL SCHEMAS IN DATABASE NOVADRIVE TO ROLE USER_READONLY;

GRANT SELECT ON ALL TABLES IN DATABASE NOVADRIVE TO ROLE USER_READONLY;

GRANT SELECT ON FUTURE TABLES IN DATABASE NOVADRIVE TO ROLE USER_READONLY;